
// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/64472e94dfb5719eeb9299eb
###
GET http://localhost:8080/contacts/64472ed9dfb5719eeb9299ec
###
GET http://localhost:8080/contacts/64472f62dfb5719eeb9299ed
###
GET http://localhost:8080/contacts/64472f8bdfb5719eeb9299ee

// PRODUCTION Deploy
###
GET https://#/contacts
###
GET https://#/contacts/64472e94dfb5719eeb9299eb
###
GET https://#/contacts/64472ed9dfb5719eeb9299ec
###
GET https://#/contacts/64472f62dfb5719eeb9299ed
###
GET https://#/contacts/64472f8bdfb5719eeb9299ee