// LOCALHOST
// GET all contacts
GET http://localhost:8080/contacts HTTP/1.1

### Get contact by id 
GET http://localhost:8080/contacts/6449d9dfc34e81520e9ea0c9 HTTP/1.1

### Get contact by id 
GET http://localhost:8080/contacts/6449d9dfc34e81520e9ea0cb HTTP/1.1


### Create contact 
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

    {
        "firstName": "Niyi",
        "lastName": "Jeremy",
        "email": "njpasser@gmail.com", 
        "favoriteColor": "Brown",
        "birthday": "01/03/89"
    }

### Update contact 
PUT http://localhost:8080/contacts/6449d9dfc34e81520e9ea0cb HTTP/1.1
content-type: application/json

    {
        "firstName": "Danny",
        "lastName": "Grey",
        "email": "dgdanny@gmail.com", 
        "favoriteColor": "Grey",
        "birthday": "07/01/98"
    }
### DELETE contact 
DELETE http://localhost:8080/contacts/644c84775c0403a65827b48d HTTP/1.1




// PRODUCTION Deploy

###
GET https://cse341-peacel03.onrender.com/contacts HTTP/1.1

### Get contact by id 
GET https://cse341-peacel03.onrender.com/contacts/6449d9dfc34e81520e9ea0c9 HTTP/1.1

### Get contact by id 
GET https://cse341-peacel03.onrender.com/contacts/6449d9dfc34e81520e9ea0cb HTTP/1.1


### Create contact 
POST https://cse341-peacel03.onrender.com/contacts HTTP/1.1
content-type: application/json
    {
        "firstName": "Niyi",
        "lastName": "Jeremy",
        "email": "njpasser@gmail.com", 
        "favoriteColor": "Brown",
        "birthday": "01/03/89"
    }

### Update contact 
PUT https://cse341-peacel03.onrender.com/contacts/6449d9dfc34e81520e9ea0cc HTTP/1.1
content-type: application/json

    {
        "firstName": "Danny",
        "lastName": "Grey",
        "email": "dgdanny@gmail.com", 
        "favoriteColor": "Black",
        "birthday": "07/01/98"
    }
### DELETE contact 
DELETE https://cse341-peacel03.onrender.com/contacts/644c84775c0403a65827b48d HTTP/1.1
